apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample
  labels:
    app: go-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-sample
  template:
    spec:
      imagePullSecrets:
        - name: regcred
    metadata:
      labels:
        app: go-sample
    spec:
      containers:
        - name: go-sample
          image: ghcr.io/walnuts1018/go-sample-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
