apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-status-api
  labels:
    app: machine-status-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-status-api
  template:
    spec:
      imagePullSecrets:
        - name: regcred
    metadata:
      labels:
        app: machine-status-api
    spec:
      containers:
        - name: machine-status-api
          image: ghcr.io/walnuts1018/machine-status-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      nodeSelector:
          kubernetes.io/hostname: kurumi-01
