name: Run the docker image build
on:
  release:
      types: [published]
  workflow_dispatch:
  
jobs:
  build:
    name: Run the docker image build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          version: latest
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main
      
      - name: Get Tag from Release
        run: echo "ImageTag=${GITHUB_REF##*/}" >> $GITHUB_ENV
       
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        if: github.event_name == 'release'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/walnuts1018/machine-status-api:latest
            ghcr.io/walnuts1018/machine-status-api:${{ env.ImageTag }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        if: github.event_name != 'release'
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/walnuts1018/machine-status-api:test-latest
            ghcr.io/walnuts1018/machine-status-api:test-${{ github.sha }}-${{ github.run_number }}

  NotifySucceed:
    if: ${{ success() }}
    name: Notify succeed
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Nofity build succeed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: Build docker image of machine-status-api succeeded
          SLACK_MESSAGE: 'https://github.com/walnuts1018/machine-status-api/pkgs/container/machine-status-api'
           
  NotifyFailure:
    if: ${{ failure() }}
    name: Notify failure
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Nofity build failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: Build docker image of machine-status-api  failed
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'Run number : #${{ github.run_number }}'
